/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Venn;

public class Library {
    public boolean someLibraryMethod() {
        return true;

        // change
        // Testing
        //dfkjhvjdf
        // something else
        // Test
        // Nice
        //Last test commit

    }
    //change
}
